add: Cost functions depend on input length for more functions
blockstack/clarity-benchmarking pull request #20
Opened 2021-09-21 20:46 UTC by gregorycoppola

Fixes #16

We add dependence on input size for the following functions:

```
cost_fetch_entry
cost_set_entry
cost_fetch_var
cost_set_var
cost_list_cons
cost_hash160
cost_sha256
cost_sha512
cost_sha512t256
cost_keccak256
cost_print
```

2021-09-27 19:25 UTC, gregorycoppola commented
I have graphed the data from the functions changed in this PR. First of all, I assessed the goodness of a linear fit using an R^2 test:
https://docs.google.com/spreadsheets/d/1aZd546onPBoTFeYmpsFUSCyuWoddgPkbiWwgIrHs6AE/edit#gid=438584037

The results are here
```
cost_list_cons | 0.9997255645
cost_keccak256 | 0.9989829175
cost_hash160 | 0.9982778497
cost_sha256 | 0.9980671802
cost_sha512 | 0.9960817095
cost_sha512t256 | 0.9951421714
cost_print | 0.9792520071            <----- last linear value
cost_set_entry | 0.1130263704     <----- not that linear
cost_fetch_var | 0.03193181877
cost_set_var | 0.005442961763
cost_fetch_entry | 0.001998854447
```

As we can see, a linear fit is very explanatory for 7/11 of the functions, but then it starts to drop off for the others.

I've attached graphs of the linear fit for these curves. We see the same story as with the R^2. For some functions, it's not that great of a fit.

[PR 20 images.zip](https://github.com/blockstack/clarity-benchmarking/files/7238771/PR.20.images.zip)
.

2021-10-04 15:02 UTC, pavitthrap requested changes
Need to take a look at how the cost functions are invoked in the code base to determine how to interpret input size.

2021-10-04 15:02 UTC, pavitthrap commented on src/generators.rs
> +    for i in 0..input_size {
Input size is not being accurately interpreted here: 
```
runtime_cost(
        ClarityCostFunction::SetVar,
        env,
        data_types.value_type.size(),
    )?;
```

2021-10-12 15:12 UTC, gregorycoppola commented
Seems like there are a lot of errors in here :/, so will close for Reed to salvage what he can.

2021-10-12 15:12 UTC, closed without merging